---
title: "Unemployment Claims Animated"
author: "Jason Smith"
date: "5/2/2020"
output: github_document

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#setup work

```{r}
library(tidyverse)
library(gganimate)
library(readxl)
library(gifski)
setwd("C:\\Users\\Jason\\OneDrive\\Documents\\R Projects\\Unemployment graph")

unemployment <- read_excel("Unemployment.xlsx")

unemployment$week <- as.Date(unemployment$week, origin="1899-12-30")
```
#Create the graph

```{r}
graph <- ggplot(data = unemployment, aes(x=week, y=claims, group=1))+
  geom_line()+
  geom_point(color="red", size = 3)+
  theme_classic()+
  scale_y_continuous(labels = scales::comma)+
  scale_x_date(date_labels = "%B, %Y")+
  labs(title = "U.S. Unemployment Claims (1967- April 2020)", x = "Time", y = "Claims")+
  theme(axis.title = element_text(size = 15, face = "bold"), title = element_text(size=20, face = 'bold'))
```
#Animate and save

```{r}
anim <- graph+
  transition_reveal(week)+
  ease_aes('bounce-out')+
  view_follow()

options(gganimate.dev_args = list(width=800, height=600))

animate(anim, nframes = 300, end_pause = 10, renderer = gifski_renderer("unemployment_graph.gif"))

```

